version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka 
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gateway:
    image: aznu/micro-travel-booking
    ports:
      - "8090:8090"
    depends_on:
      - kafka
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: gateway
  hotel:
    image: aznu/micro-travel-booking
    depends_on:
      - kafka
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: hotel
  flight:
    image: aznu/micro-travel-booking
    depends_on:
      - kafka
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: flight
  payment:
    image: aznu/micro-travel-booking
    depends_on:
      - kafka
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: payment

