//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 01:47:49 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://flight.bp.org/")
package org.bp.flight;
